### ISSUE TITLE
fswebcam should return non-zero on failure

### ISSUE THREAD

**Issue by dannyman** [fsphil/fswebcam#33]
```
djh@djh-dell-p5510:~/fswebcam$ fswebcam -q -d /dev/video10
stat: No such file or directory
djh@djh-dell-p5510:~/fswebcam$ echo $?
0
```

Use case is a cron:

`fswebcam -q -d /dev/video1 -r 1920x1080 /home/djh/Dropbox/webcam/\%Y\%m\%d/\%H\%M.png || fswebcam -q -d /dev/video0 -r 1920x1080 /home/djh/Dropbox/webcam/\%Y\%m\%d/\%H\%M.png`

The idea is if the external webcam isn't hooked up, use the portable computer's internal webcam. But when fswebcam fails to open video1, it simply returns 0.

**Comment by dannyman** [comment]
Cron workaround:
`fswebcam -q -d /dev/video1 -r 1920x1080 /home/djh/Dropbox/webcam/\%Y\%m\%d/\%H\%M.png ; test -f /home/djh/Dropbox/webcam/`date +\%Y\%m\%d/\%H\%M` || fswebcam -q -d /dev/video0 -r 1920x1080 /home/djh/Dropbox/webcam/\%Y\%m\%d/\%H\%M.png`

**Comment by fsphil** [comment]
Agreed. Fixed in 1ce8598, returns -1 if the capture fails.

**Comment by dannyman** [comment]
<3 Thanks!

**Comment by Buadhai** [comment]
I still get zero even on an error:

```
pi@rasp2:~/webcam $ fswebcam --version
fswebcam 20140113
pi@rasp2:~/webcam $ fswebcam -d /dev/video4 test.jpg
--- Opening /dev/video4...
stat: No such file or directory
pi@rasp2:~/webcam $ echo $?
0

```

**Comment by Buadhai** [comment]
Never mind, I got it. This one worked: sudo apt install libgd-dev

```
pi@rasp2:~/webcam $ fswebcam --version
fswebcam 20140113
pi@rasp2:~/webcam $ fswebcam -d /dev/video4 text.jpg
--- Opening /dev/video4...
stat: No such file or directory
pi@rasp2:~/webcam $ echo $?
255
```

**Comment by Buadhai** [comment]
Except, I still have a problem:

Here's my config file:

## config file for fswebcam

```
device /dev/video0
input 0
resolution 1920×1080
no-banner
## jpeg 90
## delay 5
skip 200
frames 3
## background
save  /home/pi/webcam/webcam.jpg
```

If I run that with the version of fswebcam that I installed with apt, it produces an image that is 1920x1280:

```
pi@rasp2:~/webcam $ /usr/bin/fswebcam -c fswebcam.conf
--- Opening /dev/video0...
Trying source module v4l2...
/dev/video0 opened.
Adjusting resolution from 1920x-1 to 1920x1080.
```

 But, if I run the fswebcam that I compiled it says:

```
pi@rasp2:~/webcam $ /usr/bin/fswebcambak -c fswebcam.conf
--- Opening /dev/video0...
Trying source module v4l2...
/dev/video0 opened.
Adjusting resolution from 1920x1 to 320x240.
```

So it inexplicably changes the resolution to 320x240.

What am I doing wrong here?

**Comment by fsphil** [comment]
The config you pasted has a unicode multiplication character in 1920×1080. Try a regular x, 1920x1080.
